from __future__ import annotations
"""
MCP Builder — generates a complete, standalone MCP server from contract ABI.
"""

import json
import os
import re
from .analyzer import categorize_functions, identify_contract_type, solidity_type_to_python, function_to_tool_name


def generate_mcp_server(
    contract_data: dict,
    output_dir: str,
    name: str | None = None,
) -> str:
    """
    Generate a complete MCP server directory from contract data.
    
    Args:
        contract_data: Output from abi_fetcher.fetch_contract_data()
        output_dir: Where to write the generated server
        name: Human-friendly name (e.g., "Trader Joe Router")
    
    Returns:
        Path to generated server directory
    """
    os.makedirs(output_dir, exist_ok=True)

    address = contract_data["address"]
    chain = contract_data["chain"]
    abi = contract_data["abi"]
    contract_type = identify_contract_type(abi)
    categories = categorize_functions(abi)
    
    if not name:
        name = f"{contract_type['description']} ({address[:8]}...)"

    # Generate files
    _write_server_py(output_dir, address, chain, name, abi, categories, contract_data, contract_type)
    _write_requirements(output_dir)
    _write_abi_json(output_dir, abi)
    _write_readme(output_dir, address, chain, name, categories, contract_type, contract_data)
    _write_env_example(output_dir, contract_data)

    return output_dir


def _write_server_py(output_dir, address, chain, name, abi, categories, contract_data, contract_type):
    """Generate the main server.py with MCP tools for each ABI function."""
    
    read_tools = _generate_read_tools(categories["read"], address)
    write_tools = _generate_write_tools(categories["write"], address, contract_data["native_token"])
    
    server_code = f'''"""
{name} — MCP Server
Auto-generated by AvaPilot (https://github.com/avapilot/avapilot)

Contract: {address}
Chain: {contract_data["chain_name"]}
Type: {contract_type["description"]}
"""

import json
import os
from mcp.server.fastmcp import FastMCP
from web3 import Web3

# --- Configuration ---
CONTRACT_ADDRESS = "{address}"
RPC_URL = os.getenv("RPC_URL", "{contract_data['rpc_url']}")
CHAIN_ID = {contract_data["chain_id"]}

# Load ABI
_abi_path = os.path.join(os.path.dirname(__file__), "abi.json")
with open(_abi_path) as f:
    CONTRACT_ABI = json.load(f)

# --- Web3 helpers ---
def _get_w3():
    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    if not w3.is_connected():
        raise ConnectionError(f"Cannot connect to RPC: {{RPC_URL}}")
    return w3

def _get_contract(w3=None):
    if w3 is None:
        w3 = _get_w3()
    addr = Web3.to_checksum_address(CONTRACT_ADDRESS)
    return w3.eth.contract(address=addr, abi=CONTRACT_ABI)

def _convert_arg(value, sol_type: str):
    """Convert a value to the appropriate Python type for a Solidity type."""
    if sol_type.startswith("uint") or sol_type.startswith("int"):
        return int(value) if not isinstance(value, int) else value
    elif sol_type == "address":
        return Web3.to_checksum_address(str(value))
    elif sol_type == "bool":
        if isinstance(value, str):
            return value.lower() in ("true", "1", "yes")
        return bool(value)
    elif sol_type.endswith("[]"):
        inner_type = sol_type[:-2]
        return [_convert_arg(v, inner_type) for v in value]
    return value

# --- MCP Server ---
mcp = FastMCP("{name}")

{read_tools}

{write_tools}

if __name__ == "__main__":
    mcp.run()
'''
    
    with open(os.path.join(output_dir, "server.py"), "w") as f:
        f.write(server_code)


def _generate_read_tools(read_funcs: list, address: str) -> str:
    """Generate MCP tool functions for read (view/pure) ABI functions."""
    tools = []
    
    for func in read_funcs:
        func_name = func["name"]
        tool_name = function_to_tool_name(func_name)
        inputs = func.get("inputs", [])
        outputs = func.get("outputs", [])
        
        # Build parameter list
        params = []
        param_docs = []
        convert_lines = []
        
        for i, inp in enumerate(inputs):
            pname = inp.get("name", f"arg{i}") or f"arg{i}"
            ptype = solidity_type_to_python(inp["type"])
            params.append(f"{pname}: {ptype}")
            param_docs.append(f"        {pname}: {inp['type']}")
            convert_lines.append(f'    _convert_arg({pname}, "{inp["type"]}")')
        
        param_str = ", ".join(params)
        param_doc_str = "\n".join(param_docs)
        args_str = ", ".join(convert_lines) if convert_lines else ""
        
        # Build output description
        out_desc = ""
        if outputs:
            out_parts = [f"{o.get('name', 'result')}: {o['type']}" for o in outputs]
            out_desc = f"\n\n    Returns: {', '.join(out_parts)}"
        
        tool_code = f'''
@mcp.tool()
def {tool_name}({param_str}) -> str:
    """Read {func_name} from contract.
    
    Args:
{param_doc_str if param_doc_str else "        (no arguments)"}
    {out_desc}
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.{func_name}({args_str}).call()
        return json.dumps({{"success": True, "result": str(result)}})
    except Exception as e:
        return json.dumps({{"success": False, "error": str(e)}})
'''
        tools.append(tool_code)
    
    header = "# ═══ Read Functions ═══" if tools else ""
    return header + "\n".join(tools)


def _generate_write_tools(write_funcs: list, address: str, native_token: str) -> str:
    """Generate MCP tool functions for write (state-changing) ABI functions."""
    tools = []
    
    for func in write_funcs:
        func_name = func["name"]
        tool_name = function_to_tool_name(func_name)
        inputs = func.get("inputs", [])
        is_payable = func.get("stateMutability") == "payable"
        
        # Build parameter list
        params = []
        param_docs = []
        convert_lines = []
        
        for i, inp in enumerate(inputs):
            pname = inp.get("name", f"arg{i}") or f"arg{i}"
            ptype = solidity_type_to_python(inp["type"])
            params.append(f"{pname}: {ptype}")
            param_docs.append(f"        {pname}: {inp['type']}")
            convert_lines.append(f'    _convert_arg({pname}, "{inp["type"]}")')
        
        if is_payable:
            params.append(f"value_wei: int = 0")
            param_docs.append(f"        value_wei: Amount of {native_token} to send (in wei)")
        
        param_str = ", ".join(params)
        param_doc_str = "\n".join(param_docs)
        args_str = ", ".join(convert_lines) if convert_lines else ""
        value_line = "value_wei" if is_payable else "0"
        
        tool_code = f'''
@mcp.tool()
def {tool_name}({param_str}) -> str:
    """Build transaction for {func_name}.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
{param_doc_str if param_doc_str else "        (no arguments)"}
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [{args_str}]
        encoded = contract.functions.{func_name}(*args)._encode_transaction_data()
        tx = {{
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex({value_line}),
            "data": encoded,
            "chainId": CHAIN_ID,
        }}
        return json.dumps({{"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute {func_name}"}})
    except Exception as e:
        return json.dumps({{"success": False, "error": str(e)}})
'''
        tools.append(tool_code)
    
    header = "\n# ═══ Write Functions (returns unsigned tx) ═══" if tools else ""
    return header + "\n".join(tools)


def _write_requirements(output_dir):
    with open(os.path.join(output_dir, "requirements.txt"), "w") as f:
        f.write("mcp>=1.0.0\nweb3>=6.0.0\n")


def _write_abi_json(output_dir, abi):
    with open(os.path.join(output_dir, "abi.json"), "w") as f:
        json.dump(abi, f, indent=2)


def _write_env_example(output_dir, contract_data):
    with open(os.path.join(output_dir, ".env.example"), "w") as f:
        f.write(f"# RPC URL (defaults to {contract_data['chain_name']})\n")
        f.write(f"RPC_URL={contract_data['rpc_url']}\n")


def _write_readme(output_dir, address, chain, name, categories, contract_type, contract_data):
    n_read = len(categories["read"])
    n_write = len(categories["write"])
    n_events = len(categories["events"])
    
    read_list = "\n".join(f"- `{f['name']}` — {_describe_func(f)}" for f in categories["read"][:20])
    write_list = "\n".join(f"- `{f['name']}` — {_describe_func(f)}" for f in categories["write"][:20])
    
    readme = f"""# {name} — MCP Server

Auto-generated by [AvaPilot](https://github.com/avapilot/avapilot).

## Contract Info

| | |
|---|---|
| **Address** | `{address}` |
| **Chain** | {contract_data["chain_name"]} |
| **Type** | {contract_type["description"]} |
| **Verified** | {"✅ Yes" if contract_data.get("verified") else "⚠️ No"} |

## Tools

**{n_read} read tools** (query on-chain state):
{read_list}

**{n_write} write tools** (build unsigned transactions):
{write_list}

## Quick Start

```bash
# Install dependencies
pip install -r requirements.txt

# Run the MCP server
python server.py
```

## Connect to Claude Desktop

Add to `~/Library/Application Support/Claude/claude_desktop_config.json`:

```json
{{
  "mcpServers": {{
    "{function_to_tool_name(name.split()[0].lower())}": {{
      "command": "python",
      "args": ["{os.path.abspath(output_dir)}/server.py"],
      "env": {{
        "RPC_URL": "{contract_data['rpc_url']}"
      }}
    }}
  }}
}}
```

## Connect to OpenClaw

Add the MCP server config to your OpenClaw setup to let your agent interact with this contract.

---

*Generated by AvaPilot v0.1.0*
"""
    with open(os.path.join(output_dir, "README.md"), "w") as f:
        f.write(readme)


def _describe_func(func: dict) -> str:
    """Generate a short description of a function from its ABI."""
    inputs = func.get("inputs", [])
    outputs = func.get("outputs", [])
    
    in_str = ", ".join(f"{i.get('name', '?')}: {i['type']}" for i in inputs)
    out_str = ", ".join(o["type"] for o in outputs)
    
    mutability = func.get("stateMutability", "")
    payable = " 💰 payable" if mutability == "payable" else ""
    
    return f"({in_str}) → {out_str}{payable}"
