"""
Trader Joe Router — MCP Server
Auto-generated by AvaPilot (https://github.com/avapilot/avapilot)

Contract: 0x60aE616a2155Ee3d9A68541Ba4544862310933d4
Chain: Avalanche C-Chain
Type: DEX router for token swapping
"""

import json
import os
from mcp.server.fastmcp import FastMCP
from web3 import Web3

# --- Configuration ---
CONTRACT_ADDRESS = "0x60aE616a2155Ee3d9A68541Ba4544862310933d4"
RPC_URL = os.getenv("RPC_URL", "https://api.avax.network/ext/bc/C/rpc")
CHAIN_ID = 43114

# Load ABI
_abi_path = os.path.join(os.path.dirname(__file__), "abi.json")
with open(_abi_path) as f:
    CONTRACT_ABI = json.load(f)

# --- Web3 helpers ---
def _get_w3():
    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    if not w3.is_connected():
        raise ConnectionError(f"Cannot connect to RPC: {RPC_URL}")
    return w3

def _get_contract(w3=None):
    if w3 is None:
        w3 = _get_w3()
    addr = Web3.to_checksum_address(CONTRACT_ADDRESS)
    return w3.eth.contract(address=addr, abi=CONTRACT_ABI)

def _convert_arg(value, sol_type: str):
    """Convert a value to the appropriate Python type for a Solidity type."""
    if sol_type.startswith("uint") or sol_type.startswith("int"):
        return int(value) if not isinstance(value, int) else value
    elif sol_type == "address":
        return Web3.to_checksum_address(str(value))
    elif sol_type == "bool":
        if isinstance(value, str):
            return value.lower() in ("true", "1", "yes")
        return bool(value)
    elif sol_type.endswith("[]"):
        inner_type = sol_type[:-2]
        return [_convert_arg(v, inner_type) for v in value]
    return value

# --- MCP Server ---
mcp = FastMCP("Trader Joe Router")

# ═══ Read Functions ═══
@mcp.tool()
def w_a_v_a_x() -> str:
    """Read WAVAX from contract.
    
    Args:
        (no arguments)
    

    Returns: : address
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.WAVAX().call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def factory() -> str:
    """Read factory from contract.
    
    Args:
        (no arguments)
    

    Returns: : address
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.factory().call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def get_amount_in(amountOut: int, reserveIn: int, reserveOut: int) -> str:
    """Read getAmountIn from contract.
    
    Args:
        amountOut: uint256
        reserveIn: uint256
        reserveOut: uint256
    

    Returns: amountIn: uint256
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.getAmountIn(    _convert_arg(amountOut, "uint256"),     _convert_arg(reserveIn, "uint256"),     _convert_arg(reserveOut, "uint256")).call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def get_amount_out(amountIn: int, reserveIn: int, reserveOut: int) -> str:
    """Read getAmountOut from contract.
    
    Args:
        amountIn: uint256
        reserveIn: uint256
        reserveOut: uint256
    

    Returns: amountOut: uint256
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.getAmountOut(    _convert_arg(amountIn, "uint256"),     _convert_arg(reserveIn, "uint256"),     _convert_arg(reserveOut, "uint256")).call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def get_amounts_in(amountOut: int, path: list[str]) -> str:
    """Read getAmountsIn from contract.
    
    Args:
        amountOut: uint256
        path: address[]
    

    Returns: amounts: uint256[]
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.getAmountsIn(    _convert_arg(amountOut, "uint256"),     _convert_arg(path, "address[]")).call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def get_amounts_out(amountIn: int, path: list[str]) -> str:
    """Read getAmountsOut from contract.
    
    Args:
        amountIn: uint256
        path: address[]
    

    Returns: amounts: uint256[]
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.getAmountsOut(    _convert_arg(amountIn, "uint256"),     _convert_arg(path, "address[]")).call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def quote(amountA: int, reserveA: int, reserveB: int) -> str:
    """Read quote from contract.
    
    Args:
        amountA: uint256
        reserveA: uint256
        reserveB: uint256
    

    Returns: amountB: uint256
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.quote(    _convert_arg(amountA, "uint256"),     _convert_arg(reserveA, "uint256"),     _convert_arg(reserveB, "uint256")).call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})



# ═══ Write Functions (returns unsigned tx) ═══
@mcp.tool()
def add_liquidity(tokenA: str, tokenB: str, amountADesired: int, amountBDesired: int, amountAMin: int, amountBMin: int, to: str, deadline: int) -> str:
    """Build transaction for addLiquidity.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        tokenA: address
        tokenB: address
        amountADesired: uint256
        amountBDesired: uint256
        amountAMin: uint256
        amountBMin: uint256
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(tokenA, "address"),     _convert_arg(tokenB, "address"),     _convert_arg(amountADesired, "uint256"),     _convert_arg(amountBDesired, "uint256"),     _convert_arg(amountAMin, "uint256"),     _convert_arg(amountBMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.addLiquidity(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute addLiquidity"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def add_liquidity_a_v_a_x(token: str, amountTokenDesired: int, amountTokenMin: int, amountAVAXMin: int, to: str, deadline: int, value_wei: int = 0) -> str:
    """Build transaction for addLiquidityAVAX.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        token: address
        amountTokenDesired: uint256
        amountTokenMin: uint256
        amountAVAXMin: uint256
        to: address
        deadline: uint256
        value_wei: Amount of AVAX to send (in wei)
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(token, "address"),     _convert_arg(amountTokenDesired, "uint256"),     _convert_arg(amountTokenMin, "uint256"),     _convert_arg(amountAVAXMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.addLiquidityAVAX(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(value_wei),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute addLiquidityAVAX"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity(tokenA: str, tokenB: str, liquidity: int, amountAMin: int, amountBMin: int, to: str, deadline: int) -> str:
    """Build transaction for removeLiquidity.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        tokenA: address
        tokenB: address
        liquidity: uint256
        amountAMin: uint256
        amountBMin: uint256
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(tokenA, "address"),     _convert_arg(tokenB, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountAMin, "uint256"),     _convert_arg(amountBMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.removeLiquidity(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidity"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity_a_v_a_x(token: str, liquidity: int, amountTokenMin: int, amountAVAXMin: int, to: str, deadline: int) -> str:
    """Build transaction for removeLiquidityAVAX.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        token: address
        liquidity: uint256
        amountTokenMin: uint256
        amountAVAXMin: uint256
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(token, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountTokenMin, "uint256"),     _convert_arg(amountAVAXMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.removeLiquidityAVAX(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidityAVAX"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity_a_v_a_x_supporting_fee_on_transfer_tokens(token: str, liquidity: int, amountTokenMin: int, amountAVAXMin: int, to: str, deadline: int) -> str:
    """Build transaction for removeLiquidityAVAXSupportingFeeOnTransferTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        token: address
        liquidity: uint256
        amountTokenMin: uint256
        amountAVAXMin: uint256
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(token, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountTokenMin, "uint256"),     _convert_arg(amountAVAXMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.removeLiquidityAVAXSupportingFeeOnTransferTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidityAVAXSupportingFeeOnTransferTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity_a_v_a_x_with_permit(token: str, liquidity: int, amountTokenMin: int, amountAVAXMin: int, to: str, deadline: int, approveMax: bool, v: int, r: str, s: str) -> str:
    """Build transaction for removeLiquidityAVAXWithPermit.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        token: address
        liquidity: uint256
        amountTokenMin: uint256
        amountAVAXMin: uint256
        to: address
        deadline: uint256
        approveMax: bool
        v: uint8
        r: bytes32
        s: bytes32
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(token, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountTokenMin, "uint256"),     _convert_arg(amountAVAXMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256"),     _convert_arg(approveMax, "bool"),     _convert_arg(v, "uint8"),     _convert_arg(r, "bytes32"),     _convert_arg(s, "bytes32")]
        encoded = contract.functions.removeLiquidityAVAXWithPermit(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidityAVAXWithPermit"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity_a_v_a_x_with_permit_supporting_fee_on_transfer_tokens(token: str, liquidity: int, amountTokenMin: int, amountAVAXMin: int, to: str, deadline: int, approveMax: bool, v: int, r: str, s: str) -> str:
    """Build transaction for removeLiquidityAVAXWithPermitSupportingFeeOnTransferTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        token: address
        liquidity: uint256
        amountTokenMin: uint256
        amountAVAXMin: uint256
        to: address
        deadline: uint256
        approveMax: bool
        v: uint8
        r: bytes32
        s: bytes32
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(token, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountTokenMin, "uint256"),     _convert_arg(amountAVAXMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256"),     _convert_arg(approveMax, "bool"),     _convert_arg(v, "uint8"),     _convert_arg(r, "bytes32"),     _convert_arg(s, "bytes32")]
        encoded = contract.functions.removeLiquidityAVAXWithPermitSupportingFeeOnTransferTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidityAVAXWithPermitSupportingFeeOnTransferTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def remove_liquidity_with_permit(tokenA: str, tokenB: str, liquidity: int, amountAMin: int, amountBMin: int, to: str, deadline: int, approveMax: bool, v: int, r: str, s: str) -> str:
    """Build transaction for removeLiquidityWithPermit.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        tokenA: address
        tokenB: address
        liquidity: uint256
        amountAMin: uint256
        amountBMin: uint256
        to: address
        deadline: uint256
        approveMax: bool
        v: uint8
        r: bytes32
        s: bytes32
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(tokenA, "address"),     _convert_arg(tokenB, "address"),     _convert_arg(liquidity, "uint256"),     _convert_arg(amountAMin, "uint256"),     _convert_arg(amountBMin, "uint256"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256"),     _convert_arg(approveMax, "bool"),     _convert_arg(v, "uint8"),     _convert_arg(r, "bytes32"),     _convert_arg(s, "bytes32")]
        encoded = contract.functions.removeLiquidityWithPermit(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute removeLiquidityWithPermit"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_a_v_a_x_for_exact_tokens(amountOut: int, path: list[str], to: str, deadline: int, value_wei: int = 0) -> str:
    """Build transaction for swapAVAXForExactTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountOut: uint256
        path: address[]
        to: address
        deadline: uint256
        value_wei: Amount of AVAX to send (in wei)
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountOut, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapAVAXForExactTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(value_wei),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapAVAXForExactTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_a_v_a_x_for_tokens(amountOutMin: int, path: list[str], to: str, deadline: int, value_wei: int = 0) -> str:
    """Build transaction for swapExactAVAXForTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
        value_wei: Amount of AVAX to send (in wei)
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactAVAXForTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(value_wei),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactAVAXForTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_a_v_a_x_for_tokens_supporting_fee_on_transfer_tokens(amountOutMin: int, path: list[str], to: str, deadline: int, value_wei: int = 0) -> str:
    """Build transaction for swapExactAVAXForTokensSupportingFeeOnTransferTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
        value_wei: Amount of AVAX to send (in wei)
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactAVAXForTokensSupportingFeeOnTransferTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(value_wei),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactAVAXForTokensSupportingFeeOnTransferTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_tokens_for_a_v_a_x(amountIn: int, amountOutMin: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapExactTokensForAVAX.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountIn: uint256
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountIn, "uint256"),     _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactTokensForAVAX(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactTokensForAVAX"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_tokens_for_a_v_a_x_supporting_fee_on_transfer_tokens(amountIn: int, amountOutMin: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapExactTokensForAVAXSupportingFeeOnTransferTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountIn: uint256
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountIn, "uint256"),     _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactTokensForAVAXSupportingFeeOnTransferTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactTokensForAVAXSupportingFeeOnTransferTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_tokens_for_tokens(amountIn: int, amountOutMin: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapExactTokensForTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountIn: uint256
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountIn, "uint256"),     _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactTokensForTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactTokensForTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_exact_tokens_for_tokens_supporting_fee_on_transfer_tokens(amountIn: int, amountOutMin: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapExactTokensForTokensSupportingFeeOnTransferTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountIn: uint256
        amountOutMin: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountIn, "uint256"),     _convert_arg(amountOutMin, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapExactTokensForTokensSupportingFeeOnTransferTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapExactTokensForTokensSupportingFeeOnTransferTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_tokens_for_exact_a_v_a_x(amountOut: int, amountInMax: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapTokensForExactAVAX.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountOut: uint256
        amountInMax: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountOut, "uint256"),     _convert_arg(amountInMax, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapTokensForExactAVAX(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapTokensForExactAVAX"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def swap_tokens_for_exact_tokens(amountOut: int, amountInMax: int, path: list[str], to: str, deadline: int) -> str:
    """Build transaction for swapTokensForExactTokens.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        amountOut: uint256
        amountInMax: uint256
        path: address[]
        to: address
        deadline: uint256
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(amountOut, "uint256"),     _convert_arg(amountInMax, "uint256"),     _convert_arg(path, "address[]"),     _convert_arg(to, "address"),     _convert_arg(deadline, "uint256")]
        encoded = contract.functions.swapTokensForExactTokens(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute swapTokensForExactTokens"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


if __name__ == "__main__":
    mcp.run()
