"""
USDC on Avalanche — MCP Server
Auto-generated by AvaPilot (https://github.com/avapilot/avapilot)

Contract: 0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E
Chain: Avalanche C-Chain
Type: Custom contract
"""

import json
import os
from mcp.server.fastmcp import FastMCP
from web3 import Web3

# --- Configuration ---
CONTRACT_ADDRESS = "0xB97EF9Ef8734C71904D8002F8b6Bc66Dd9c48a6E"
RPC_URL = os.getenv("RPC_URL", "https://api.avax.network/ext/bc/C/rpc")
CHAIN_ID = 43114

# Load ABI
_abi_path = os.path.join(os.path.dirname(__file__), "abi.json")
with open(_abi_path) as f:
    CONTRACT_ABI = json.load(f)

# --- Web3 helpers ---
def _get_w3():
    w3 = Web3(Web3.HTTPProvider(RPC_URL))
    if not w3.is_connected():
        raise ConnectionError(f"Cannot connect to RPC: {RPC_URL}")
    return w3

def _get_contract(w3=None):
    if w3 is None:
        w3 = _get_w3()
    addr = Web3.to_checksum_address(CONTRACT_ADDRESS)
    return w3.eth.contract(address=addr, abi=CONTRACT_ABI)

def _convert_arg(value, sol_type: str):
    """Convert a value to the appropriate Python type for a Solidity type."""
    if sol_type.startswith("uint") or sol_type.startswith("int"):
        return int(value) if not isinstance(value, int) else value
    elif sol_type == "address":
        return Web3.to_checksum_address(str(value))
    elif sol_type == "bool":
        if isinstance(value, str):
            return value.lower() in ("true", "1", "yes")
        return bool(value)
    elif sol_type.endswith("[]"):
        inner_type = sol_type[:-2]
        return [_convert_arg(v, inner_type) for v in value]
    return value

# --- MCP Server ---
mcp = FastMCP("USDC on Avalanche")

# ═══ Read Functions ═══
@mcp.tool()
def admin() -> str:
    """Read admin from contract.
    
    Args:
        (no arguments)
    

    Returns: : address
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.admin().call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def implementation() -> str:
    """Read implementation from contract.
    
    Args:
        (no arguments)
    

    Returns: : address
    """
    try:
        w3 = _get_w3()
        contract = _get_contract(w3)
        result = contract.functions.implementation().call()
        return json.dumps({"success": True, "result": str(result)})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})



# ═══ Write Functions (returns unsigned tx) ═══
@mcp.tool()
def change_admin(newAdmin: str) -> str:
    """Build transaction for changeAdmin.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        newAdmin: address
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(newAdmin, "address")]
        encoded = contract.functions.changeAdmin(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute changeAdmin"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def upgrade_to(newImplementation: str) -> str:
    """Build transaction for upgradeTo.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        newImplementation: address
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(newImplementation, "address")]
        encoded = contract.functions.upgradeTo(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(0),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute upgradeTo"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


@mcp.tool()
def upgrade_to_and_call(newImplementation: str, data: str, value_wei: int = 0) -> str:
    """Build transaction for upgradeToAndCall.
    
    Returns an unsigned transaction object. The user must sign and broadcast it.
    
    Args:
        newImplementation: address
        data: bytes
        value_wei: Amount of AVAX to send (in wei)
    """
    try:
        w3 = Web3()
        contract = w3.eth.contract(
            address=Web3.to_checksum_address(CONTRACT_ADDRESS),
            abi=CONTRACT_ABI
        )
        args = [    _convert_arg(newImplementation, "address"),     _convert_arg(data, "bytes")]
        encoded = contract.functions.upgradeToAndCall(*args)._encode_transaction_data()
        tx = {
            "to": Web3.to_checksum_address(CONTRACT_ADDRESS),
            "value": hex(value_wei),
            "data": encoded,
            "chainId": CHAIN_ID,
        }
        return json.dumps({"success": True, "transaction": tx, "description": "Sign and broadcast this transaction to execute upgradeToAndCall"})
    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})


if __name__ == "__main__":
    mcp.run()
